### ISSUE TITLE
teslarati.com is unresolved

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardDNS#277]
Original issue - https://github.com/AdguardTeam/AdguardFilters/issues/16585

>www.teslarati.com is unresolved using Adguard DNS but resolves correctly when using 8.8.8.8
So I think Adguard DNS IS blocking it (although it's a legit news site)

### Steps to reproduce

1. Go here - https://www.teslarati.com/

### Expected behavior

Website should works

### Actual behavior

Website is unresolved

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/40319095-33529fe4-5d27-11e8-96f1-bba82e8fb9cc.png)

![image](https://user-images.githubusercontent.com/29142494/40319105-3a1e70be-5d27-11e8-8db9-362c396586e2.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| 176.103.130.130
| How did you setup DNS configuration:| System
| Device model:| -
| Operating system and version:| Windows 10

**Comment by wiz0u** [comment]
It seems fixed now (I didn't change anything by my side)

**Comment by AdamWr** [comment]
Strange, I checked it a moment ago and it didn't worked on my end and still doesn't work.

**Comment by wiz0u** [comment]
Oh now it's not working anymore. What the..

**Comment by wiz0u** [comment]
Here are the requests I just made. Within the last 10 min it worked and then stopped resolving. 
![screenshot_20180521-190004](https://user-images.githubusercontent.com/11647984/40319719-6b6d23fc-5d29-11e8-9034-42fb54efa057.png)

**Comment by wiz0u** [comment]
The screenshot doesnt show clearly but i confirm i was using nameserver 176.103.130.130

**Comment by wiz0u** [comment]
The "timed out" is when I tried with 176.103.130.131

**Comment by wiz0u** [comment]
(same issue on my PC... teslarati.com worked 10 minutes ago, and now it's not working)

**Comment by wiz0u** [comment]
...and now it's working (!)

**Comment by wiz0u** [comment]
now teslarati.com resolves, but not www.teslarati.com

```
nslookup www.teslarati.com
Serveur :   176-103-130-130.flops.ru
Address:  176.103.130.130

*** 176-103-130-130.flops.ru ne parvient pas à trouver www.teslarati.com : Non-existent domain

nslookup teslarati.com
Serveur :   176-103-130-130.flops.ru
Address:  176.103.130.130

Réponse ne faisant pas autorité :
Nom :    teslarati.com
Address:  50.112.249.163
```

**Comment by wiz0u** [comment]
seems solved now.

**Comment by ameshkov** [comment]
Weird issue. Seems to be working just okay at the moment.
