### ISSUE TITLE
Email autofill not detected on login page for iOS Safari

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#319]
When tapping the email box to login, autofill should appear with my AdGuard login details.

Once the email is entered by manually using autofill, the password is entered correctly.

When on the verification code page, this then suffers the same issue as #314.

![image](https://user-images.githubusercontent.com/95468948/182242274-401533d4-0acb-4664-9cdc-3998a3b46004.png)

**Comment by Batman2814** [comment]
Is the with Apple auto fill because I use Lastpass and it does auto fill for me

**Comment by Chinaski1** [comment]
It looks like the issue has been solved. Could you check and confirm that it is no longer reproducing?

**Comment by jslawler** [comment]
> It looks like the issue has been solved. Could you check and confirm that it is no longer reproducing?

Hi @Chinaski1, no the issue still exists.

![image](https://user-images.githubusercontent.com/95468948/208131730-a76c0dd9-3e56-4e50-9caa-c40b713b0efb.png)

**Comment by Chinaski1** [comment]
Fixed at [v2.2.1](https://adguard-dns.io/en/versions.html#2.2.1)
